// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentApp.Data;

#nullable disable

namespace StudentApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentApp.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Students", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 20,
                            Email = "zhangsan@example.com",
                            EnrollmentDate = new DateTime(2025, 11, 16, 8, 58, 15, 579, DateTimeKind.Local).AddTicks(8221),
                            Name = "张三"
                        },
                        new
                        {
                            Id = 2,
                            Age = 22,
                            Email = "lisi@example.com",
                            EnrollmentDate = new DateTime(2025, 11, 26, 8, 58, 15, 579, DateTimeKind.Local).AddTicks(8234),
                            Name = "李四"
                        },
                        new
                        {
                            Id = 3,
                            Age = 21,
                            Email = "wangwu@example.com",
                            EnrollmentDate = new DateTime(2025, 12, 6, 8, 58, 15, 579, DateTimeKind.Local).AddTicks(8236),
                            Name = "王五"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
